#!/bin/bash

export COMP_WORDBREAKS=${COMP_WORDBREAKS/\:/}

_kronk() 
{
  local cur kronk_keys

  cur="${COMP_WORDS[COMP_CWORD]}"

  kronk_keys="$HOME/.kronk_history"

  if [ -f "$kronk_keys" ]; then
    COMPREPLY=( $(compgen -W "$(cat $kronk_keys)" -- ${cur}) )
    return 0
  fi

  return 1
}

complete -o default -F _kronk kronk
